stages:
  - install
  - test
  - build
  - docker

variables:
  NODE_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  image: node:20
  script:
    - npm ci --no-audit --no-fund
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

test:
  stage: test
  image: node:20
  dependencies:
    - install
  script:
    - npm test -- --coverage
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      cobertura: coverage/cobertura-coverage.xml

build:
  stage: build
  image: node:20
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

docker:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t sk8/spotservice:ci .

